// This file is auto-generated by Remix's route config
import type {
  LoaderArgs,
  ActionArgs,
  ComponentProps,
  MetaArgs,
} from "react-router";

export interface Route {
  params: {}
}

export interface LoaderArgs extends LoaderArgs {
  params: Route.params
}

export interface ActionArgs extends ActionArgs {
  params: Route.params
}

export interface ComponentProps {
  loaderData: never
}

export interface MetaArgs extends MetaArgs<{
  matches: [
    {
      params: Route.params
    }
  ]
}, {}> {
}
